/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Tablero;
import Modelos.Random;
import javax.swing.JPanel;
/**
 *
 * @author Proyecto Diseño
 */
public class DadosTurnoPrincipio extends javax.swing.JFrame {
	private int num1;
	private int num2;
	private int resultado; 
	/**
	 * Creates new form DadosTurnoPrincipio
	 */
	public DadosTurnoPrincipio() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txfDado1 = new javax.swing.JTextField();
        txfDado2 = new javax.swing.JTextField();
        btnTirarDados = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 153));

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));

        txfDado1.setEditable(false);
        txfDado1.setFont(new java.awt.Font("Courier New", 0, 36)); // NOI18N
        txfDado1.setForeground(new java.awt.Color(0, 0, 0));
        txfDado1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfDado1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txfDado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfDado1ActionPerformed(evt);
            }
        });

        txfDado2.setEditable(false);
        txfDado2.setFont(new java.awt.Font("Courier New", 0, 36)); // NOI18N
        txfDado2.setForeground(new java.awt.Color(0, 0, 0));
        txfDado2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfDado2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txfDado2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfDado2ActionPerformed(evt);
            }
        });

        btnTirarDados.setBackground(new java.awt.Color(255, 51, 51));
        btnTirarDados.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        btnTirarDados.setForeground(new java.awt.Color(0, 0, 0));
        btnTirarDados.setText("Tirar Dados");
        btnTirarDados.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnTirarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTirarDadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(txfDado1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(txfDado2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(btnTirarDados, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfDado1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfDado2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(btnTirarDados, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txfDado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfDado1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfDado1ActionPerformed

    private void txfDado2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfDado2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfDado2ActionPerformed

    private void btnTirarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTirarDadosActionPerformed
        num1 = Random.randomInt(1, 6);
		num2 = Random.randomInt(1, 6);
		txfDado1.setText(Integer.toString(num1));
		txfDado2.setText(Integer.toString(num2));
		resultado = num1 + num2;
		btnTirarDados.setEnabled(false);
    }//GEN-LAST:event_btnTirarDadosActionPerformed

	public int getResultado() {
		return resultado;
	}

	public JPanel getPanel() {
		return jPanel1;
	}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTirarDados;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txfDado1;
    private javax.swing.JTextField txfDado2;
    // End of variables declaration//GEN-END:variables
}
