/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Tablero;

import Modelos.Personaje;
import java.util.ArrayList;

/**
 *
 * @author Proyecto Diseño
 */
public class ElegirPersonajeAtacar extends javax.swing.JPanel {
	Personaje enemigoElegido;
	ArrayList<Personaje> contrincantes;
	/**
	 * Creates new form ElegirPersonajeAtacar
	 */
	public ElegirPersonajeAtacar(Personaje personaAtacando, ArrayList<Personaje> personajes) {
		initComponents();
		contrincantes = new ArrayList<Personaje>();
		ponerEnemigosEnArrayList(personaAtacando, personajes);
		ponerPersonajesEnCbx();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbxContrincantes = new javax.swing.JComboBox<>();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(cbxContrincantes, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(145, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(cbxContrincantes, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


	private void ponerEnemigosEnArrayList(Personaje personaAtacando, ArrayList<Personaje> personajes){
		contrincantes.add(null);
		for (Personaje personajeEnArrayList : personajes) {
			if(!personajeEnArrayList.equals(personaAtacando)){
				contrincantes.add(personajeEnArrayList);
			}
		}
	}
	private void ponerPersonajesEnCbx(){
		
		for (Personaje contrincante : contrincantes) {
			if(contrincante == null){
				cbxContrincantes.addItem("Elija Personaje");
				continue;
			}
			cbxContrincantes.addItem(contrincante.getNombre());
		}
	}

	public Personaje getEnemigoElegido() {
		return contrincantes.get(cbxContrincantes.getSelectedIndex());
	}
	
	
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxContrincantes;
    // End of variables declaration//GEN-END:variables
}
