/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Juegos;

import Modelos.Random;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Proyecto Diseño
 */
public class PantallaPath extends javax.swing.JFrame implements ActionListener{
	private boolean jugando;
	private int intentos = 3;
	private int filasFaltantes=5;
	JButton[][] casillas = new JButton[3][6];
	ImageIcon casillaIcon = new ImageIcon(getClass().getResource("/Pics/bloquePregunta.png"));
	ImageIcon checkIcon = new ImageIcon(getClass().getResource("/Pics/checkmark.png"));
	private boolean perdio;
	
	public PantallaPath() {
		jugando = true;
		initComponents();
		ponerBotones();
		ponerCorrectos();
		enableBotones();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlJuego = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout pnlJuegoLayout = new javax.swing.GroupLayout(pnlJuego);
        pnlJuego.setLayout(pnlJuegoLayout);
        pnlJuegoLayout.setHorizontalGroup(
            pnlJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 216, Short.MAX_VALUE)
        );
        pnlJuegoLayout.setVerticalGroup(
            pnlJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 451, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlJuego, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlJuego, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(PantallaPath.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(PantallaPath.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(PantallaPath.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(PantallaPath.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new PantallaPath().setVisible(true);
			}
		});
	}
	
	private void ponerBotones(){
		for (int i = 0; i < 3; i++) {
			for (int j = 0; j < 6; j++) {
				JButton boton = new JButton(casillaIcon);
				casillas[i][j] = boton;
				pnlJuego.add(boton);
				boton.setBounds(i*55,j*55,50,50);
				boton.addActionListener(this);
				boton.setEnabled(true);
			}
		}
	}
	
	private void ponerCorrectos(){
		for (int fila = 0; fila < 6; fila++) {
			int num = Random.randomInt(0, 2);
			for (int col = 0; col < 3; col++) {
				if(num == col){
					casillas[col][fila].setRolloverIcon(checkIcon);
					break;
				}
			}
		}
	}
	
	private void enableBotones(){
		for (int i = 0; i < 6; i++) {
			for (int j = 0; j < 3; j++) {
				casillas[j][i].setEnabled(false);
				if(i == filasFaltantes){
					casillas[j][i].setEnabled(true);
				}
			}
		}
		filasFaltantes--;
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlJuego;
    // End of variables declaration//GEN-END:variables

	@Override
	public void actionPerformed(ActionEvent evt) {
		JButton boton =(JButton) evt.getSource();
		if(boton.getRolloverIcon()!=null){
            
            if(filasFaltantes == -1){
                JOptionPane.showInternalMessageDialog(null, "HAS GANADO");
                jugando = false;
				this.setVisible(false);
				perdio = false;
                return;
            }
            
            enableBotones();
            return;
        }
		if(intentos !=1){
			filasFaltantes = 5;
			enableBotones();
			intentos--;
			return;
		} else{
			JOptionPane.showInternalMessageDialog(null, "HAS PERDIDO");
            jugando = false;
			this.setVisible(false);
			perdio = true;
            return;
		}
	}

	public boolean isJugando() {
		return jugando;
	}
	
	public boolean isPerdio() {
		return perdio;
	}
	
}
