/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Juegos;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import Modelos.Random;
import javax.swing.JOptionPane;
/**
 *
 * @author Proyecto Diseño
 */
public class PantallaGuess extends javax.swing.JFrame {
	ImageIcon preguntaIcon = new ImageIcon(getClass().getResource("/Pics/bloquePregunta.png"));
	private boolean jugando;
	private int celdasAQuitar;
	private int personajeAdivinar;
	private boolean perdio;
	/**
	 * Creates new form PantallaGuess
	 */
	public PantallaGuess() {
		initComponents();
		this.jugando = true;
		this.celdasAQuitar = Random.randomInt(4, 8);
		this.personajeAdivinar = Random.randomInt(0, 14);
		lblIntentos.setText("Intentos: " + celdasAQuitar);
		ponerPersonaje();
		ponerCeldas();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txpPersonaje = new javax.swing.JTextPane();
        cbxPersonajes = new javax.swing.JComboBox<>();
        btnElegir = new javax.swing.JButton();
        lblIntentos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(txpPersonaje);

        cbxPersonajes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Birdo", "Boo", "Bowser", "Diddy", "Dimentio", "Donkey Kong", "Dr. Mario", "Dry Bones", "Goomba", "Mario", "Pirana", "Toad", "Waluigi", "Wario", "Yoshi" }));

        btnElegir.setText("Elegir personaje");
        btnElegir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElegirActionPerformed(evt);
            }
        });

        lblIntentos.setText("Intentos: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblIntentos, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(cbxPersonajes, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62))))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                        .addComponent(btnElegir, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblIntentos, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110)
                .addComponent(cbxPersonajes, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnElegir, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnElegirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElegirActionPerformed
        if(cbxPersonajes.getSelectedIndex() == personajeAdivinar){
			JOptionPane.showMessageDialog(this, "Ganaste el juego","", 1);
			perdio = false;
		} else {
			JOptionPane.showMessageDialog(this, "Perdiste el juego","", 0);
			perdio = true;
		}
		
		this.jugando = false;
		this.setVisible(false);
    }//GEN-LAST:event_btnElegirActionPerformed

	private void ponerPersonaje(){
		switch(personajeAdivinar) {
			case 0:
				txpPersonaje.insertIcon(new ImageIcon(getClass().getResource("/Pics/GuessWho/birdo.png")));
				break;
			case 1:
				txpPersonaje.insertIcon(new ImageIcon(getClass().getResource("/Pics/GuessWho/boo.png")));
				break;
			case 2:
				txpPersonaje.insertIcon(new ImageIcon(getClass().getResource("/Pics/GuessWho/bowser.png")));
				break;
			case 3:
				txpPersonaje.insertIcon(new ImageIcon(getClass().getResource("/Pics/GuessWho/diddy.png")));
				break;
			case 4:
				txpPersonaje.insertIcon(new ImageIcon(getClass().getResource("/Pics/GuessWho/dimentio.png")));
				break;
			case 5:
				txpPersonaje.insertIcon(new ImageIcon(getClass().getResource("/Pics/GuessWho/donkeykong.png")));
				break;
			case 6:
				txpPersonaje.insertIcon(new ImageIcon(getClass().getResource("/Pics/GuessWho/drmario.png")));
				break;
			case 7:
				txpPersonaje.insertIcon(new ImageIcon(getClass().getResource("/Pics/GuessWho/drybones.png")));
				break;
			case 8:
				txpPersonaje.insertIcon(new ImageIcon(getClass().getResource("/Pics/GuessWho/goomba.png")));
				break;
			case 9:
				txpPersonaje.insertIcon(new ImageIcon(getClass().getResource("/Pics/GuessWho/mario.png")));
				break;
			case 10:
				txpPersonaje.insertIcon(new ImageIcon(getClass().getResource("/Pics/GuessWho/pirana.png")));
				break;
			case 11:
				txpPersonaje.insertIcon(new ImageIcon(getClass().getResource("/Pics/GuessWho/toad.png")));
				break;
			case 12:
				txpPersonaje.insertIcon(new ImageIcon(getClass().getResource("/Pics/GuessWho/waluigi.png")));
				break;
			case 13:
				txpPersonaje.insertIcon(new ImageIcon(getClass().getResource("/Pics/GuessWho/wario.png")));
				break;
			case 14:
				txpPersonaje.insertIcon(new ImageIcon(getClass().getResource("/Pics/GuessWho/yoshi.png")));
				break;
		}
	}
	
	private void ponerCeldas(){
		for (int i = 0; i < 10; i++) {
			for (int j = 0; j < 10; j++) {
				JButton boton = new JButton(preguntaIcon);
				txpPersonaje.add(boton);
				boton.setBounds(10+52*i,10+52*j,50,50);
				
				boton.addMouseListener(new MouseAdapter() {
                public void mouseClicked(MouseEvent evt) {
                    ponerInvisible(evt);
                }
                });
			}
		}
	}
	
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(PantallaGuess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(PantallaGuess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(PantallaGuess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(PantallaGuess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new PantallaGuess().setVisible(true);
			}
		});
	}
	
	private void ponerInvisible(MouseEvent evento){
		if(celdasAQuitar == 0){
			return;
		}
		JButton boton = (JButton)evento.getComponent();
		boton.setIcon(null);
		boton.setOpaque(false);
		boton.setContentAreaFilled(false);
		boton.setBorderPainted(false);
		celdasAQuitar-=1;
		lblIntentos.setText("Intentos: " + celdasAQuitar);
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnElegir;
    private javax.swing.JComboBox<String> cbxPersonajes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblIntentos;
    private javax.swing.JTextPane txpPersonaje;
    // End of variables declaration//GEN-END:variables

	public boolean isJugando() {
		return jugando;
	}
	
	public boolean isPerdio() {
		return perdio;
	}
	
}
