/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Juegos;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Proyecto Diseño
 */
public class PantallaCards extends javax.swing.JFrame implements ActionListener{
	JButton[][] botones = new JButton[13][4];
	ImageIcon cartaIcon = new ImageIcon(getClass().getResource("/Pics/carta.png"));
	int cartaType = -1;
	int cartaNum = -1;
	/**
	 * Creates new form PantallaCards
	 */
	public PantallaCards() {
		initComponents();
		ponerBotones();
	}

	String toStringType(int num) {
		switch(num) {
			case 0: 
				return "Diamantes";
			case 1: 
				return "Espadas";
			case 2: 
				return "Trebloes";

			case 3: 
				return "Corazones";
			default:
				return "";
		}
	}

	String toStringNum(int num) {
		switch(num) {
			case 0: 
				return "Dos";
			case 1: 
				return "Tres";
			case 2: 
				return "Cuatro";
			case 3: 
				return "Cinco";
			case 4: 
				return "Seis";
			case 5: 
				return "Siete";
			case 6: 
				return "Ocho";
			case 7: 
				return "Nueve";
			case 8: 
				return "Diez";
			case 9: 
				return "J";
			case 10: 
				return "Q";
			case 11: 
				return "K";
			case 12: 
				return "A";
			default:
				return "";
		}
	
	}

	
	private void ponerBotones(){
		for (int i = 0; i < 13; i++) {
			for (int j = 0; j < 4; j++) {
				botones[i][j] = new JButton(cartaIcon);
				JButton boton = botones[i][j];
				pnlCards.add(boton);
				boton.setBounds(20+38*i,20+58*j,33,53);
				boton.addActionListener(this);
			}
		}
	}
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCards = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout pnlCardsLayout = new javax.swing.GroupLayout(pnlCards);
        pnlCards.setLayout(pnlCardsLayout);
        pnlCardsLayout.setHorizontalGroup(
            pnlCardsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );
        pnlCardsLayout.setVerticalGroup(
            pnlCardsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(pnlCards, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(pnlCards, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(PantallaCards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(PantallaCards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(PantallaCards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(PantallaCards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new PantallaCards().setVisible(true);
			}
		});
	}
	
	public boolean cartaElegida(){
		if(cartaType == -1 || cartaType == -1){
			return false;
		} else{
			return true;
		}
	}

	public int getCartaType() {
		return cartaType;
	}

	public int getCartaNum() {
		return cartaNum;
	}

	
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlCards;
    // End of variables declaration//GEN-END:variables

	@Override
	public void actionPerformed(ActionEvent e) {
		JButton boton = (JButton)e.getSource();
		for (int i = 0; i < 4; i++) {
			for (int j = 0; j < 13; j++) {
				if(boton == botones[j][i]){
					cartaType = i;
					cartaNum = j;
					JOptionPane.showMessageDialog(this, toStringNum(cartaNum) + " de " + toStringType(cartaType), "Escogida", 1);
					this.setVisible(false);
					return;
				}
			}
		}
	}
}
