/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Cliente;

import java.util.ArrayList;
import javax.swing.JButton;

/**
 *
 * @author Proyecto Diseño
 */
public class ElegirPersonaje extends javax.swing.JPanel {

	ArrayList<Integer> disponibles;
	private int elegido;
	
	public ElegirPersonaje(ArrayList<Integer> disponibles) {
		initComponents();
		this.disponibles = disponibles;
		elegido = -1;
		botonesInvisibles();
		ponerVisiblesPersonajes();
		
	}
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn0Mario = new javax.swing.JButton();
        btn1MrL = new javax.swing.JButton();
        btn2Peach = new javax.swing.JButton();
        btn3Toad = new javax.swing.JButton();
        btn4Yoshi = new javax.swing.JButton();
        btn5Luma = new javax.swing.JButton();
        btn6Bowser = new javax.swing.JButton();
        btn7Daisy = new javax.swing.JButton();
        btn8Rosalina = new javax.swing.JButton();
        btn9Dimentio = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(587, 238));

        btn0Mario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/PaperMarioTransparente78x100.png"))); // NOI18N
        btn0Mario.setMaximumSize(new java.awt.Dimension(110, 110));
        btn0Mario.setMinimumSize(new java.awt.Dimension(110, 110));
        btn0Mario.setPreferredSize(new java.awt.Dimension(110, 110));
        btn0Mario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0MarioActionPerformed(evt);
            }
        });

        btn1MrL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/MrLTransparente67x100.png"))); // NOI18N
        btn1MrL.setMaximumSize(new java.awt.Dimension(110, 110));
        btn1MrL.setMinimumSize(new java.awt.Dimension(110, 110));
        btn1MrL.setPreferredSize(new java.awt.Dimension(110, 110));
        btn1MrL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1MrLActionPerformed(evt);
            }
        });

        btn2Peach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/PeachTransparente95x100.png"))); // NOI18N
        btn2Peach.setMaximumSize(new java.awt.Dimension(110, 110));
        btn2Peach.setMinimumSize(new java.awt.Dimension(110, 110));
        btn2Peach.setPreferredSize(new java.awt.Dimension(110, 110));
        btn2Peach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2PeachActionPerformed(evt);
            }
        });

        btn3Toad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/ToadTransparente62x100.png"))); // NOI18N
        btn3Toad.setMaximumSize(new java.awt.Dimension(110, 110));
        btn3Toad.setMinimumSize(new java.awt.Dimension(110, 110));
        btn3Toad.setPreferredSize(new java.awt.Dimension(110, 110));
        btn3Toad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ToadActionPerformed(evt);
            }
        });

        btn4Yoshi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/YoshiTransparente86x100.png"))); // NOI18N
        btn4Yoshi.setMaximumSize(new java.awt.Dimension(110, 110));
        btn4Yoshi.setMinimumSize(new java.awt.Dimension(110, 110));
        btn4Yoshi.setPreferredSize(new java.awt.Dimension(110, 110));
        btn4Yoshi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4YoshiActionPerformed(evt);
            }
        });

        btn5Luma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/LumaTransparente98x100.png"))); // NOI18N
        btn5Luma.setMaximumSize(new java.awt.Dimension(110, 110));
        btn5Luma.setMinimumSize(new java.awt.Dimension(110, 110));
        btn5Luma.setPreferredSize(new java.awt.Dimension(110, 110));
        btn5Luma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5LumaActionPerformed(evt);
            }
        });

        btn6Bowser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/BowserTransparente100x100.png"))); // NOI18N
        btn6Bowser.setMaximumSize(new java.awt.Dimension(110, 110));
        btn6Bowser.setMinimumSize(new java.awt.Dimension(110, 110));
        btn6Bowser.setPreferredSize(new java.awt.Dimension(110, 110));
        btn6Bowser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6BowserActionPerformed(evt);
            }
        });

        btn7Daisy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/DaisyTransparente84x100.png"))); // NOI18N
        btn7Daisy.setMaximumSize(new java.awt.Dimension(110, 110));
        btn7Daisy.setMinimumSize(new java.awt.Dimension(110, 110));
        btn7Daisy.setPreferredSize(new java.awt.Dimension(110, 110));
        btn7Daisy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7DaisyActionPerformed(evt);
            }
        });

        btn8Rosalina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/RosalinaTransparente58x100.png"))); // NOI18N
        btn8Rosalina.setMaximumSize(new java.awt.Dimension(110, 110));
        btn8Rosalina.setMinimumSize(new java.awt.Dimension(110, 110));
        btn8Rosalina.setPreferredSize(new java.awt.Dimension(110, 110));
        btn8Rosalina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8RosalinaActionPerformed(evt);
            }
        });

        btn9Dimentio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/DimentioTransparente100x87.png"))); // NOI18N
        btn9Dimentio.setMaximumSize(new java.awt.Dimension(110, 110));
        btn9Dimentio.setMinimumSize(new java.awt.Dimension(110, 110));
        btn9Dimentio.setPreferredSize(new java.awt.Dimension(110, 110));
        btn9Dimentio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9DimentioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn0Mario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn1MrL, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn2Peach, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(btn3Toad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn4Yoshi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn5Luma, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn6Bowser, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn7Daisy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn8Rosalina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn9Dimentio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btn2Peach, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn4Yoshi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn3Toad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn1MrL, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn0Mario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn7Daisy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn5Luma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn6Bowser, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn9Dimentio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn8Rosalina, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn0MarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0MarioActionPerformed
        ((JButton)evt.getSource()).setVisible(false);
        quitarDeDisponibles(0);
    }//GEN-LAST:event_btn0MarioActionPerformed

    private void btn1MrLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1MrLActionPerformed
        ((JButton)evt.getSource()).setVisible(false);
        quitarDeDisponibles(1);
    }//GEN-LAST:event_btn1MrLActionPerformed

    private void btn2PeachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2PeachActionPerformed
        ((JButton)evt.getSource()).setVisible(false);
        quitarDeDisponibles(2);
    }//GEN-LAST:event_btn2PeachActionPerformed

    private void btn3ToadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ToadActionPerformed
        ((JButton)evt.getSource()).setVisible(false);
        quitarDeDisponibles(3);
    }//GEN-LAST:event_btn3ToadActionPerformed

    private void btn4YoshiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4YoshiActionPerformed
        ((JButton)evt.getSource()).setVisible(false);
        quitarDeDisponibles(4);
    }//GEN-LAST:event_btn4YoshiActionPerformed

    private void btn5LumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5LumaActionPerformed
        ((JButton)evt.getSource()).setVisible(false);
        quitarDeDisponibles(5);
    }//GEN-LAST:event_btn5LumaActionPerformed

    private void btn6BowserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6BowserActionPerformed
        ((JButton)evt.getSource()).setVisible(false);
        quitarDeDisponibles(6);
    }//GEN-LAST:event_btn6BowserActionPerformed

    private void btn7DaisyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7DaisyActionPerformed
        ((JButton)evt.getSource()).setVisible(false);
        quitarDeDisponibles(7);
    }//GEN-LAST:event_btn7DaisyActionPerformed

    private void btn8RosalinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8RosalinaActionPerformed
        ((JButton)evt.getSource()).setVisible(false);
        quitarDeDisponibles(8);
    }//GEN-LAST:event_btn8RosalinaActionPerformed

    private void btn9DimentioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9DimentioActionPerformed
        ((JButton)evt.getSource()).setVisible(false);
        quitarDeDisponibles(9);
    }//GEN-LAST:event_btn9DimentioActionPerformed

	private void quitarDeDisponibles(int personaje){
		for (Integer disponible : disponibles) {
			if(personaje == disponible){
				disponibles.remove(disponible);
				break;
			}
		}
		
		this.elegido = personaje;
		disableBotones();
	}
	
	private void disableBotones() {
		btn0Mario.setEnabled(false);
		btn1MrL.setEnabled(false);
		btn2Peach.setEnabled(false);
		btn3Toad.setEnabled(false);
		btn4Yoshi.setEnabled(false);
		btn5Luma.setEnabled(false);
		btn6Bowser.setEnabled(false);
		btn7Daisy.setEnabled(false);
		btn8Rosalina.setEnabled(false);
		btn9Dimentio.setEnabled(false);
	}
	
	private void botonesInvisibles(){
		btn0Mario.setVisible(false);
		btn1MrL.setVisible(false);
		btn2Peach.setVisible(false);
		btn3Toad.setVisible(false);
		btn4Yoshi.setVisible(false);
		btn5Luma.setVisible(false);
		btn6Bowser.setVisible(false);
		btn7Daisy.setVisible(false);
		btn8Rosalina.setVisible(false);
		btn9Dimentio.setVisible(false);
	}
	
	private void ponerVisiblesPersonajes(){ //pone visibles a los personajes existentes
		for (Integer disponible : disponibles) {
			switch (disponible) {
				case 0:
					btn0Mario.setVisible(true);
					break;
				case 1:
					btn1MrL.setVisible(true);
					break;
				case 2:
					btn2Peach.setVisible(true);
					break;
				case 3:
					btn3Toad.setVisible(true);
					break;
				case 4:
					btn4Yoshi.setVisible(true);
					break;
				case 5:
					btn5Luma.setVisible(true);
					break;
				case 6:
					btn6Bowser.setVisible(true);
					break;
				case 7:
					btn7Daisy.setVisible(true);
					break;
				case 8:
					btn8Rosalina.setVisible(true);
					break;
				case 9:
					btn9Dimentio.setVisible(true);
					break;
				default:
					System.out.println("Invalid option");
					break;
			}
		}
	}
	
	public int getElegido() {
		return elegido;
	}

	public ArrayList<Integer> getDisponibles() {
		return disponibles;
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0Mario;
    private javax.swing.JButton btn1MrL;
    private javax.swing.JButton btn2Peach;
    private javax.swing.JButton btn3Toad;
    private javax.swing.JButton btn4Yoshi;
    private javax.swing.JButton btn5Luma;
    private javax.swing.JButton btn6Bowser;
    private javax.swing.JButton btn7Daisy;
    private javax.swing.JButton btn8Rosalina;
    private javax.swing.JButton btn9Dimentio;
    // End of variables declaration//GEN-END:variables
}
